### PR TITLE
Add aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Add aarch64 wheel build support.
Related to https://github.com/ndparker/rjsmin/issues/24 @ndparker Could you please review this PR?

### CODE REVIEW

**Comment by odidev** [comment]
@ndparker, Could you please have a look at this PR?

**Comment by odidev** [comment]
@ndparker Could you please review this PR? Thanks in advance.

**Comment by madhukarkumarpuresoftware** [comment]
@ndparker Could you please review this PR?

**Comment by odidev** [comment]
@ndparker Could you please review this PR?

**Comment by ndparker** [comment]
Hi,

thanks for the idea. I don't like adding another shellscript, though, so I've included it into the invoke task in this branch: https://github.com/ndparker/rjsmin/compare/aarch64

Let me know what you think.

**Comment by odidev** [comment]
> Let me know what you think.

Changes looks ok to me.

**Comment by ndparker** [comment]
Thanks. 1.2.0 has been released and includes aarch64 wheels now.

**Pull request closed without merging**
